# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.6.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFormLayout, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QTabWidget,
    QTextBrowser, QTextEdit, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1985, 951)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1991, 1121))
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QFont()
        font.setFamilies([u"RobotoMono Nerd Font Propo [GOOG]"])
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(u"")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label_3 = QLabel(self.tab_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(80, 130, 111, 31))
        font1 = QFont()
        font1.setFamilies([u"RobotoMono Nerd Font Propo [GOOG]"])
        font1.setPointSize(16)
        self.label_3.setFont(font1)
        self.submitButton = QPushButton(self.tab_3)
        self.submitButton.setObjectName(u"submitButton")
        self.submitButton.setGeometry(QRect(530, 130, 171, 31))
        font2 = QFont()
        font2.setFamilies([u"RobotoMono Nerd Font Md [GOOG]"])
        font2.setPointSize(13)
        self.submitButton.setFont(font2)
        self.formLayoutWidget_2 = QWidget(self.tab_3)
        self.formLayoutWidget_2.setObjectName(u"formLayoutWidget_2")
        self.formLayoutWidget_2.setGeometry(QRect(70, 180, 301, 201))
        self.formLayout = QFormLayout(self.formLayoutWidget_2)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.lineEdit = QLineEdit(self.formLayoutWidget_2)
        self.lineEdit.setObjectName(u"lineEdit")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy1)
        font3 = QFont()
        font3.setFamilies([u"RobotoMono Nerd Font Propo [GOOG]"])
        font3.setPointSize(12)
        self.lineEdit.setFont(font3)

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.lineEdit)

        self.comboBox = QComboBox(self.formLayoutWidget_2)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy2)
        self.comboBox.setMinimumSize(QSize(100, 0))
        font4 = QFont()
        font4.setFamilies([u"RobotoMono Nerd Font Propo [GOOG]"])
        font4.setPointSize(13)
        self.comboBox.setFont(font4)

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.comboBox)

        self.addButton = QPushButton(self.tab_3)
        self.addButton.setObjectName(u"addButton")
        self.addButton.setGeometry(QRect(370, 130, 141, 31))
        self.addButton.setFont(font4)
        self.label_6 = QLabel(self.tab_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(230, 130, 111, 31))
        self.label_6.setFont(font1)
        self.tableName = QLineEdit(self.tab_3)
        self.tableName.setObjectName(u"tableName")
        self.tableName.setGeometry(QRect(290, 70, 221, 31))
        font5 = QFont()
        font5.setFamilies([u"RobotoMono Nerd Font Propo [GOOG]"])
        font5.setPointSize(24)
        self.tableName.setFont(font5)
        self.output = QTextBrowser(self.tab_3)
        self.output.setObjectName(u"output")
        self.output.setGeometry(QRect(450, 190, 256, 192))
        self.label_4 = QLabel(self.tab_3)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(80, 60, 201, 51))
        font6 = QFont()
        font6.setFamilies([u"RobotoMono Nerd Font Propo [GOOG]"])
        font6.setPointSize(24)
        font6.setBold(False)
        self.label_4.setFont(font6)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.pushButton_2 = QPushButton(self.tab_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(50, 50, 141, 26))
        self.textEdit = QTextEdit(self.tab_2)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(50, 90, 301, 211))
        self.pushButton_3 = QPushButton(self.tab_2)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(350, 370, 161, 26))
        self.pushButton_4 = QPushButton(self.tab_2)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(50, 350, 141, 26))
        self.pushButton_5 = QPushButton(self.tab_2)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(350, 340, 161, 26))
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1985, 23))
        self.menuQUERY_TOOL = QMenu(self.menubar)
        self.menuQUERY_TOOL.setObjectName(u"menuQUERY_TOOL")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuQUERY_TOOL.menuAction())

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Attribute", None))
        self.submitButton.setText(QCoreApplication.translate("MainWindow", u"CREATE DATABASE", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Integer", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"String", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Array", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"Set", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("MainWindow", u"Bool", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("MainWindow", u"Float", None))
        self.comboBox.setItemText(6, QCoreApplication.translate("MainWindow", u"Number", None))
        self.comboBox.setItemText(7, QCoreApplication.translate("MainWindow", u"Record", None))
        self.comboBox.setItemText(8, QCoreApplication.translate("MainWindow", u"DateTime", None))

        self.addButton.setText(QCoreApplication.translate("MainWindow", u"ADD ATTRIBUTE", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"DATA TYPE", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"TABLE NAME", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Page", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"BEGIN TRANSACTION", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"CANCEL TRANSACTION", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"ADD TRANSACTION", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"COMMIT TRANSACTION", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Tab 2", None))
        self.menuQUERY_TOOL.setTitle(QCoreApplication.translate("MainWindow", u"&QUERY TOOL", None))
    # retranslateUi

